[build]
  command = "yarn build"
  publish = "build"
  functions = "netlify/functions"
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
