// src/pageTemplates.js

// Each template has an id, a human‑friendly name, and
// a `slots` array of zero‑based indices into the 10 CSS slot positions.
export const pageTemplates = [
    {
        id: 0,
        name: '1‑Up (Full‑Bleed)',
        slots: [0, 1, 2],
        thumbnailUrl: '/layout-0.png',
    },
    {
        id: 1,
        name: '2‑Up (Side‑by‑Side)',
        slots: [3, 4],
        thumbnailUrl: '/layout-1.png',
    },
    {
        id: 2,
        name: '4‑Up (Grid 2×2)',
        slots: [5, 6, 7, 8],
        thumbnailUrl: '/layout-2.png',
    },
    {
        id: 3,
        name: '3‑Up (Row of 3)',
        slots: [9],
        thumbnailUrl: '/layout-3.png',
    },
    {
        id: 4,
        name: '2-Up (Horizontal)',
        slots: [11, 12],
        thumbnailUrl: '/layout-4.png',
    },
    {
        id: 5,
        name: '3‑Up (Row of 3)',
        slots: [13, 14, 15],
        thumbnailUrl: '/layout-5.png',
    },
    {
        id: 6,
        name: '3‑Up (Row of 3)',
        slots: [16, 17, 18],
        thumbnailUrl: '/layout-6.png',
    },
    {
        id: 7,
        name: '3‑Up (Row of 3)',
        slots: [19, 20, 21],
        thumbnailUrl: '/layout-7.png',
    },
    {
        id: 8,
        name: '3‑Up (Row of 3)',
        slots: [22, 23, 24],
        thumbnailUrl: '/layout-8.png',
    },
    {
        id: 9,
        name: '4‑Up (Row of 4)',
        slots: [25, 26, 27, 28],
        thumbnailUrl: '/layout-9.png',
    },
    {
        id: 10,
        name: '4‑Up (Row of 4)',
        slots: [29, 30, 31, 32],
        thumbnailUrl: '/layout-10.png',
    },
    {
        id: 11,
        name: '3‑Up (Row of 3)',
        slots: [33, 34, 35],
        thumbnailUrl: '/layout-11.png',
    },
    {
        id: 12,
        name: '3‑Up (Row of 3)',
        slots: [36, 37, 38],
        thumbnailUrl: '/layout-12.png',
    },
    {
        id: 13,
        name: '6‑Up (Row of 6)',
        slots: [39, 40, 41, 42, 43, 44],
        thumbnailUrl: '/layout-13.png',
    },
    {
        id: 14,
        name: '6‑Up (Row of 6)',
        slots: [45, 46, 47, 48, 49, 50],
        thumbnailUrl: '/layout-14.png',
    },
    {
        id: 15,
        name: '4‑Up (Row of 4)',
        slots: [51, 52, 53, 54],
        thumbnailUrl: '/layout-15.png',
    },
    {
        id: 16,
        name: '4‑Up (Row of 4)',
        slots: [55, 56, 57, 58],
        thumbnailUrl: '/layout-16.png',
    },
    {
        id: 17,
        name: '5‑Up (Row of 5)',
        slots: [59, 60, 61, 62, 63],
        thumbnailUrl: '/layout-17.png',
    },
    {
        id: 18,
        name: '5‑Up (Row of 5)',
        slots: [64, 65, 61, 62, 63],
        thumbnailUrl: '/layout-18.png',
    },
    {
        id: 19,
        name: '5‑Up (Row of 5)',
        slots: [66, 67, 68, 69, 70],
        thumbnailUrl: '/layout-19.png',
    },
    {
        id: 20,
        name: '5‑Up (Row of 5)',
        slots: [66, 67, 68, 71, 72],
        thumbnailUrl: '/layout-20.png',
    },
    {
        id: 21,
        name: '9‑Up (Row of 9)',
        slots: [73, 74, 75, 76, 77, 78, 79, 80, 81],
        thumbnailUrl: '/layout-21.png',
    },
    {
        id: 22,
        name: '1‑Up (Row of 1)',
        slots: [82],
        thumbnailUrl: '/layout-22.png',
    },
    {
        id: 23,
        name: '4‑Up (Row of 4)',
        slots: [83, 84, 85, 86],
        thumbnailUrl: '/layout-23.png',
    },
    {
        id: 24,
        name: '2‑Up (Row of 2)',
        slots: [87, 88],
        thumbnailUrl: '/layout-24.png',
    },
    {
        id: 25,
        name: '3-Up (Row of 3)',
        slots: [89, 90, 91],
        thumbnailUrl: '/layout-25.png',
    },
    {
        id: 26,
        name: '1-Up (Row of 1)',
        slots: [92],
        thumbnailUrl: '/layout-26.png',
    },
    {
        id: 27,
        name: '2-Up (Row of 2)',
        slots: [93, 94],
        thumbnailUrl: '/layout-27.png',
    },
    {
        id: 28,
        name: '2-Up (Row of 2)',
        slots: [95, 96],
        thumbnailUrl: '/layout-28.png',
    },
    {
        id: 29,
        name: '1-Up (Row of 1)',
        slots: [97],
        thumbnailUrl: '/layout-29.png',
    },
    {
        id: 30,
        name: '2-Up (Row of 2)',
        slots: [98, 99],
        thumbnailUrl: '/layout-30.png',
    },
    {
        id: 31,
        name: '2-Up (Row of 2)',
        slots: [100, 101],
        thumbnailUrl: '/layout-31.png',
    },
    {
        id: 32,
        name: '8-Up (Row of 2)',
        slots: [102, 103, 104, 105, 106, 107, 108, 109],
        thumbnailUrl: '/layout-32.png',
    },
    {
        id: 33,
        name: '8-Up (Row of 2)',
        slots: [110, 111, 112, 113, 114, 115, 116, 117],
        thumbnailUrl: '/layout-33.png',
    },
    {
        id: 133,
        name: 'Half Text Half Image',
        slots: [3],
        textSlots: [4],
        thumbnailUrl: '/layout-133.png',
    },
];

